### ISSUE TITLE
property does not exists on type '{}'

### ISSUE THREAD

**Issue by andrevst** [brayoh/react-amplify#3]
https://github.com/brayoh/react-amplify/blob/dfdf9a6c62b87f88fdd3de75ddd4e18ab822a8dc/src/Containers/LoginContainer/index.tsx#L40

This error is happening in ```const { from }```

I solved it using ```as any```:

```
const { from } = location.state || {
                from: {
                  pathname: '/dashboard'
                }
              } as any;
```

**Comment by andrevst** [comment]
Great tuturial on dev BTW. Thanks

**Comment by sgrinich** [comment]
I am seeing this as well

**Comment by brayoh** [comment]
I'm not sure how I missed out on this notification, I'll make the change and update the repo. Sorry for the issue.

**Comment by zaza** [comment]
Year later, I don't see this error. Is the issue still relevant?

**Comment by brayoh** [comment]
@zaza it is not currently an issue, let me mark it as resolved.
